freebsd_instance:
  image: freebsd-13-3-release-amd64

setup: &SETUP
  env:
    HOME: /tmp # cargo cache needs it
    # Temporary workaround for https://github.com/rust-lang/rustup/issues/2774
    RUSTUP_IO_THREADS: 1
    RUSTFLAGS: -D warnings
    RUSTDOCFLAGS: -D warnings
  # Record some info about the test environment
  sysinfo_script:
    - mount
    - df -h
    - sysctl hw.model hw.ncpu hw.physmem
    - freebsd-version
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y
    - $HOME/.cargo/bin/rustup toolchain install $VERSION
    # aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""

task:
  name: FreeBSD 13.3 MSRV
  env:
    VERSION: 1.70.0
  << : *SETUP
  test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION test
    - cargo +$VERSION doc --no-deps
    # Also run tests with sudo, because some need it for mdconfig
    - sudo -E cargo test --tests
  before_cache_script: rm -rf $HOME/.cargo/registry/index

task:
  name: FreeBSD 13.3 nightly
  env:
    VERSION: nightly
  << : *SETUP
  test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION test --all-targets
    # Also run tests with sudo, because some need it for mdconfig
    - sudo -E cargo test --tests
  clippy_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION clippy --all-features --all-targets -- -D warnings
  audit_script:
    - . $HOME/.cargo/env
    # install ca_root_nss due to https://github.com/rustsec/rustsec/issues/1137
    - pkg install -y ca_root_nss cargo-audit
    - cargo audit
  # Test our minimal version spec
  minver_test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION update -Zdirect-minimal-versions
    - cargo +$VERSION check --all-targets
    - cargo +$VERSION doc --no-deps
  before_cache_script: rm -rf $HOME/.cargo/registry/index
