freebsd_instance:
  image: freebsd-11-3-stable-amd64-v20190801

task:
  name: cargo test
  env:
    # Temporary workaround for https://github.com/rust-lang/rustup/issues/2774
    RUSTUP_IO_THREADS: 1
  # Record some info about the test environment
  sysinfo_script:
    - mount
    - df -h
    - sysctl hw.model hw.ncpu hw.physmem
    - freebsd-version
  # Install Rust
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y
    - $HOME/.cargo/bin/rustup toolchain install nightly
    # In 11.3, aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1
  test_script:
    - . $HOME/.cargo/env
    - cargo test
    # Also test on nightly, to run the benchmarks
    - cargo +nightly test --all-targets
    # Also run tests with sudo, because some need it for mdconfig
    - sudo -E cargo test --tests
  # Test our minimal version spec
  minver_test_script:
    - . $HOME/.cargo/env
    - cargo +nightly update -Zminimal-versions
    - cargo +nightly check --all-targets
