[package]
name = "tokio-file"
version = "0.1.1"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/tokio-file"
documentation = "https://docs.rs/tokio-file/0.1.1"
description = """
Asynchronous file I/O for Tokio
"""
categories = ["asynchronous", "filesystem"]

[dependencies]
futures = "0.1.10"
libc = "0.2"
mio = "0.6.9"
nix = "0.9"
mio-aio = "0.1"
tokio-core = "0.1.9"

[dev-dependencies]
futures = "0.1"
getopts = "0.2"
tempdir = "0.3"
