[package]
name = "tokio-file"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
respository = "https://github.com/asomers/tokio-file"
homepage = "https://github.com/asomers/tokio-file"
description = """
Asynchronous file I/O for Tokio
"""
categories = ["asynchronous", "filesystems"]

[dependencies]
futures = "0.1.10"
libc = "0.2"
mio = { git = "https://github.com/asomers/mio", branch = "aio6" }
nix = { git = "https://github.com/nix-rust/nix", rev = "2f780ef" }
mio-aio = { git = "https://github.com/asomers/mio-aio", rev = "edda859" }
tokio-core = { path = "/home/somers/src/rust/tokio-core" }

[dev-dependencies]
getopts = "0.2"
tempdir = "0.3"
