[package]
name = "tokio-file"
version = "0.2.0-pre"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/tokio-file"
description = """
Asynchronous file I/O for Tokio
"""
categories = ["asynchronous", "filesystem"]

[dependencies]
bytes = "0.4"
futures = "0.1.10"
libc = "0.2"
mio = "0.6.13"
nix = "0.10.0"
mio-aio = { path = "/home/somers/src/rust/mio-aio" }
tokio-core = { path = "/home/somers/src/rust/tokio-core" }

[dev-dependencies]
futures = "0.1"
getopts = "0.2"
tempdir = "0.3"
