[package]
name = "tokio-file"
edition = "2018"
version = "0.6.0"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/tokio-file"
description = """
Asynchronous file I/O for Tokio
"""
categories = ["asynchronous", "filesystem"]
documentation = "https://asomers.github.io/tokio-file/tokio_file/"
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md"]

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-freebsd",
]

[dependencies]
futures = "0.3.0"
mio = "0.7.0"
nix = "0.22.0"
mio-aio = { git = "https://github.com/asomers/mio-aio", rev = "a740a87"}
tokio = { git = "https://github.com/asomers/tokio", rev = "bf4aed3", features = [ "aio" ] }

[dev-dependencies]
galvanic-test = "0.2.0"
getopts = "0.2.18"
sysctl = "0.1"
tempfile = "3.0"
tokio = { git = "https://github.com/asomers/tokio", rev = "bf4aed3", features = [ "aio", "rt" ] }

[[test]]
name = "functional"
path = "tests/file.rs"

[[test]]
name = "lio_listio_incomplete"
path = "tests/lio_listio_incomplete.rs"

[[test]]
name = "aio_write_eagain"
path = "tests/aio_write_eagain.rs"
