[package]
name = "tokio-file"
version = "0.2.0-pre"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/tokio-file"
description = """
Asynchronous file I/O for Tokio
"""
categories = ["asynchronous", "filesystem"]

[dependencies]
futures = "0.1.10"
libc = "0.2"
mio = "0.6.13"
nix = { git = "https://github.com/asomers/nix" , rev = "71fe963" }
mio-aio = { git = "git://github.com/asomers/mio-aio.git", rev = "74666b4" }
tokio = { git = "git://github.com/tokio-rs/tokio.git", rev = "1190176" }

[dev-dependencies]
divbuf = { git = "https://github.com/asomers/divbuf", rev = "70104b4" }
futures = "0.1"
getopts = "0.2"
tempdir = "0.3"
