[package]
name = "tokio-file"
edition = "2018"
version = "0.8.0"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/tokio-file"
description = """
Asynchronous file I/O for Tokio
"""
categories = ["asynchronous", "filesystem"]
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md"]

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-freebsd",
]

[dependencies]
futures = "0.3.0"
mio = "0.7.7"
nix = { version = "0.24.0", default-features = false, features = ["ioctl"] }
mio-aio = { version = "0.7.0", features = ["tokio"] }
tokio = { version = "1.12.0", features = [ "net" ] }

[dev-dependencies]
rstest = "0.11.0"
getopts = "0.2.18"
nix = { version = "0.24.0", default-features = false, features = ["ioctl", "feature", "user"] }
sysctl = "0.1"
tempfile = "3.0"
tokio = { version = "1.12.0", features = [ "net", "rt" ] }

[[test]]
name = "functional"
path = "tests/file.rs"

[[test]]
name = "lio_listio_incomplete"
path = "tests/lio_listio_incomplete.rs"

[[test]]
name = "aio_write_eagain"
path = "tests/aio_write_eagain.rs"
