[package]
name = "tokio-file"
version = "0.2.0-pre"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/tokio-file"
description = """
Asynchronous file I/O for Tokio
"""
categories = ["asynchronous", "filesystem"]

[dependencies]
futures = "0.1.10"
libc = "0.2"
mio = "0.6.13"
nix = { git = "https://github.com/nix-rust/nix", rev = "31e901b" }
mio-aio = { git = "https://github.com/asomers/mio-aio.git", rev = "8bfa2c9" }
tokio = "0.1.5"

[dev-dependencies]
divbuf = { git = "https://github.com/asomers/divbuf", rev = "70104b4" }
futures = "0.1"
getopts = "0.2"
sysctl = "0.1"
tempdir = "0.3"

[[test]]
name = "functional"
path = "tests/file.rs"

[[test]]
name = "lio_listio_incomplete"
path = "tests/lio_listio_incomplete.rs"

[[test]]
name = "aio_write_eagain"
path = "tests/aio_write_eagain.rs"
