[package]
name = "tokio-file"
edition = "2018"
version = "0.5.3-pre"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/tokio-file"
description = """
Asynchronous file I/O for Tokio
"""
categories = ["asynchronous", "filesystem"]
documentation = "https://asomers.github.io/tokio-file/tokio_file/"

[dependencies]
futures = "0.3.0"
mio = "0.6.13"
nix = { git = "https://github.com/asomers/nix", rev = "7912d9cfb10ea3a8118f00eb5a40790cdea33c8d" }
mio-aio = { git = "https://github.com/asomers/mio-aio", rev = "7096fa18b8400ba014a43be9fdc6f913263e70fa" }
tokio = { version = "0.2.0", features = [ "io-driver" ] }

[dev-dependencies]
galvanic-test = "0.2.0"
getopts = "0.2.18"
sysctl = "0.1"
tempfile = "3.0"
tokio = { version = "0.2.0", features = [ "rt-core" ] }

[[test]]
name = "functional"
path = "tests/file.rs"

[[test]]
name = "lio_listio_incomplete"
path = "tests/lio_listio_incomplete.rs"

[[test]]
name = "aio_write_eagain"
path = "tests/aio_write_eagain.rs"
