[package]
name = "tokio-file"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
respository = "https://github.com/asomers/tokio-file"
homepage = "https://github.com/asomers/tokio-file"
description = """
Asynchronous file I/O for Tokio
"""
categories = ["asynchronous", "filesystems"]

[dependencies]
futures = "0.1.10"
libc = "0.2"
mio = "0.6.9"
nix = { git = "https://github.com/nix-rust/nix", rev = "2f780ef" }
mio-aio = { git = "https://github.com/asomers/mio-aio", rev = "b841ea6" }
tokio-core = { git = "https://github.com/tokio-rs/tokio-core", rev = "c65c331" }

[dev-dependencies]
futures = "0.1"
getopts = "0.2"
tempdir = "0.3"
